### PR TITLE
Initial ROS drake package and repository information

### PR DESCRIPTION
**Pull request by j-rivero**
New ROS drake package based on just calling ament_vendor to download, build and install the version 1.24 of Drake.

In this initial phase the GUROBI, MOSEK and SNOPT components are disabled in the build using the CMake parameters. The ament_vendor uses a couple of patches to deal with issues related to clang version and to disable the assumption of platform having a libjchart2d-java package. Patches uses the Debian DEP-3 format to include metadata on the same file. Dependencies are based on the official Drake documentation and comments are in package.xml.

Together with the code there is `Dockerfile` that will build the code in a plain `jammy` image, resolving the dependencies installation using rosdep (this allow us to test the completeness/correctness  of the dependencies in `package.xml` ) and call the CMake build interface using the same parameters used by the ROS buildfarm.

In draft (@jwnimmer-tri feel free to comment) until I can test the code in a real ROS buildfarm build and check that a Drake code example builds fine.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
FYI https://github.com/RobotLocomotion/drake/releases/tag/v1.25.0 was just tagged.  We can drop the 0002 patch once we shift to that version.

**Review by jwnimmer-tri — COMMENTED** [review]
> In this initial phase the GUROBI, MOSEK and SNOPT components are disabled in the build using the CMake parameters.

Sounds good.

> The `Dockerfile.cmake_dpkg_flags` can be used to simulate the build that the ros_buildfarm will perform ...

This is great, thanks!  Once this PR is sufficiently polished, I am happy to try it locally to cross-check that it works for me.  Let me know when you think that is.

---

I posted some review discussions on the code itself.  If it's premature to review, feel free to dismiss or defer any of the comments until they are helpful.

> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6#-:-NoJ_9Ed8RnkFfYieH1b:bcbucy4)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @j-rivero)

___
*[`.entrypoint-cmake-make-with-dpkgbuildflags.sh` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6#-NoJl60aEUKBvjE3kxGB:-NoJl60aEUKBvjE3kxGC:bdu861z) ([raw file](https://github.com/RobotLocomotion/ros-drake-vendor/blob/9d1dd341b15615e28bd61e9757b94f089ed76039/.entrypoint-cmake-make-with-dpkgbuildflags.sh#L9)):*
> ```Shell
> cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_PREFIX_PATH=/opt/ros/rolling -DAMENT_PREFIX_PATH=/opt/ros/rolling -DCMAKE_INSTALL_PREFIX=/opt/ros/rolling -DCMAKE_BUILD_TYPE=None
> make -j1 || exec "$@"
> exec "$@"
> ```

nit It took me a bit of study to glean what the final two lines were accomplishing, and why `"$@"` was expanded twice.  I think the aim is just to give the user their bash prompt, whether or not the build passed?

If so, then I think there is a more straightforward spelling:



_Suggestion:_
```Shell
make -j1 || true
exec "$@"
```
___
*[`CMakeLists.txt` line 11 at r1](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6#-NoJ_PhlCRxz3t1kl_Gz:-NoJ_PhlCRxz3t1kl_H-:bv390yv) ([raw file](https://github.com/RobotLocomotion/ros-drake-vendor/blob/9d1dd341b15615e28bd61e9757b94f089ed76039/CMakeLists.txt#L11)):*
> ```CMake
>   VCS_VERSION v1.24.0
>   CMAKE_ARGS
>     -DDRAKE_IS_BUILDING_DOCUMENTATION:BOOL=OFF
> ```

nit I'm fairly certain that `-DDRAKE_IS_BUILDING_DOCUMENTATION:BOOL=OFF` is a no-op and should be removed.  Drake's CMakeLists doesn't use that flag.

(There is some Python code that checks something similar, but the CMake definitions don't propagate into Python.)
___
*[`CMakeLists.txt` line 17 at r1](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6#-NoJ_wS01Ag95sArDzDf:-NoJ_wS01Ag95sArDzDg:b51srb8) ([raw file](https://github.com/RobotLocomotion/ros-drake-vendor/blob/9d1dd341b15615e28bd61e9757b94f089ed76039/CMakeLists.txt#L17)):*
> ```CMake
>     -DWITH_USER_EIGEN:BOOL=ON
>     -DWITH_USER_FMT:BOOL=ON
>     -DWITH_USER_SPDLOG:BOOL=ON
> ```

nit Would it be typical to comment any non-default configuration settings with their justification?



_Suggestion:_
```CMake
    # At the moment, closed-source dependencies are disabled.
    -DWITH_GUROBI:BOOL=OFF
    -DWITH_MOSEK:BOOL=OFF
    -DWITH_SNOPT:BOOL=OFF
    # Drake should use the Ament version of these dependencies found by CMake,
    # not the Ubuntu version found in /usr/include.
    -DWITH_USER_EIGEN:BOOL=ON
    -DWITH_USER_FMT:BOOL=ON
    -DWITH_USER_SPDLOG:BOOL=ON
```
___
*[`Dockerfile.cmake_dpkg_flags` line 43 at r1](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6#-NoJaz2-BUv3HtsK6CzB:-NoJaz2-BUv3HtsK6CzC:b-i7397) ([raw file](https://github.com/RobotLocomotion/ros-drake-vendor/blob/9d1dd341b15615e28bd61e9757b94f089ed76039/Dockerfile.cmake_dpkg_flags#L43)):*
> ```
> COPY . ros-drake-vendor/
> 
> # RUN date
> ```

nit Possibly stray line?



_Code quote:_
```
# RUN date
```

**Review by j-rivero — COMMENTED** [review]
> I posted some review discussions on the code itself. If it's premature to review, feel free to dismiss or defer any of the comments until they are helpful.

Useful to advance in the work while we wait other PR and implementations to happen. Thanks. 

> This is great, thanks! Once this PR is sufficiently polished, I am happy to try it locally to cross-check that it works for me. Let me know when you think that is.

Not yet there but I'll change the Draft status as soon as we resolve some pending items like #3, #7 or #8. Ping you when ready but please feel free to jump in anytime if you have feedback. 

> Reviewed 2 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6#-:-NoSgwGe9UFkTVqwcENQ:btvst2s)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @j-rivero)

___
*[`.entrypoint-cmake-make-with-dpkgbuildflags.sh` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6#-NoJl60aEUKBvjE3kxGB:-Np1NHjW0d1-Qj6w0mHk:bix4us9) ([raw file](https://github.com/RobotLocomotion/ros-drake-vendor/blob/9d1dd341b15615e28bd61e9757b94f089ed76039/.entrypoint-cmake-make-with-dpkgbuildflags.sh#L9)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit It took me a bit of study to glean what the final two lines were accomplishing, and why `"$@"` was expanded twice.  I think the aim is just to give the user their bash prompt, whether or not the build passed?

If so, then I think there is a more straightforward spelling:
</blockquote></details>

done in 0ec7427d23f5bbdb10c51247d5e99f2f2181f3b7
___
*[`CMakeLists.txt` line 11 at r1](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6#-NoJ_PhlCRxz3t1kl_Gz:-Np1NQD85igOlbEfwzO6:b39h6bx) ([raw file](https://github.com/RobotLocomotion/ros-drake-vendor/blob/9d1dd341b15615e28bd61e9757b94f089ed76039/CMakeLists.txt#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I'm fairly certain that `-DDRAKE_IS_BUILDING_DOCUMENTATION:BOOL=OFF` is a no-op and should be removed.  Drake's CMakeLists doesn't use that flag.

(There is some Python code that checks something similar, but the CMake definitions don't propagate into Python.)
</blockquote></details>

done in 4f0e96415a75f3b25acfcc4d1186f62465f92e7f
___
*[`CMakeLists.txt` line 17 at r1](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6#-NoJ_wS01Ag95sArDzDf:-Np1NXtRCjfqpJWeH-9Q:btubana) ([raw file](https://github.com/RobotLocomotion/ros-drake-vendor/blob/9d1dd341b15615e28bd61e9757b94f089ed76039/CMakeLists.txt#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Would it be typical to comment any non-default configuration settings with their justification?
</blockquote></details>

done in a4cd6a9eaec5fbee6456d1d6f246ebb0987be171
___
*[`Dockerfile.cmake_dpkg_flags` line 43 at r1](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6#-NoJaz2-BUv3HtsK6CzB:-Np1Nrws8uiHgXcWxUGC:b3gxujx) ([raw file](https://github.com/RobotLocomotion/ros-drake-vendor/blob/9d1dd341b15615e28bd61e9757b94f089ed76039/Dockerfile.cmake_dpkg_flags#L43)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Possibly stray line?
</blockquote></details>

done in 98052d3facedca35b97843519b23cf2521c380b9

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @j-rivero)

**Comment by j-rivero** [comment]
I have updated the PR to use the `drake` name 0044fbd as discussed in #8 and do some other improvements:

- Improve comment formatting 6ce67e4
- Add buildtool depend on lsb-release 9d53a2d
- Patch drake-extras.cmake with comments in #7 f1ce9c5
- Use latest version 1.26.0 9a79d00
- Implement GitHub action testing and remove Dockerfile manual procedure e31f5a3

With this I'm able to compile the `drake_cmake_installed` and `drake_cmake_installed_apt`and `drake_ament_cmake_installed` from `RobotLocomotion/drake-external-examples` without touching a single line (this is being done in the GitHub actions).

With this code I'm also able to create a testing [`ros-rolling-drake` package ](https://54.191.81.129/ubuntu/building/pool/main/r/ros-rolling-drake/)in the ROS testing buildfarm [Build Status](https://build.test.ros2.org/job/Rbin_uJ64__drake__ubuntu_jammy_amd64__binary/20/) that we can install and use to build the previous examples just fine. I'm starting to be moderately confident that it could be a good candidate for more wider testing.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: modulo open discussions.

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6#-:-Nsd8Il_7ygcIFmXTnJG:b962cgu)* status: all files reviewed, 4 unresolved discussions (waiting on @j-rivero)

___
*[`.entrypoint-cmake-make-with-dpkgbuildflags.sh` line 1 at r4](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6#-Nsd1wQh6zceM_fq3i40:-Nsd1wQh6zceM_fq3i41:bjz6zfe) ([raw file](https://github.com/RobotLocomotion/ros-drake-vendor/blob/e31f5a3fa1077eb16201d9c23b63cbc2ba1f278d/.entrypoint-cmake-make-with-dpkgbuildflags.sh#L1)):*
> ```Shell
> #!/bin/bash -e
> ```

nit Now that the Dockerfile is gone, is this file dead code that should be removed?

If not, then it probably some comment at the start here to explain the context of how/where it will/should be used.
___
*[`package.xml` line 12 at r4](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6#-Nsd3qxmDyYuctSAT7Jq:-Nsd3qxmDyYuctSAT7Jr:b-82ccwv) ([raw file](https://github.com/RobotLocomotion/ros-drake-vendor/blob/e31f5a3fa1077eb16201d9c23b63cbc2ba1f278d/package.xml#L12)):*
> ```XML
>   </description>
>   <maintainer email="drake-users@mit.edu">Drake Users</maintainer>
>   <license>BSD</license>
> ```

What is the expectation for the comprehensiveness of this `<license>` element?  Certainly the majority of Drake's first-party code is `SPDX: BSD-3-Clause`, but Drake vendors a bunch of other code with various open-source licenses.

(If we still need some surgery here then that's fine, but please file a tracking issue to remind us.)
___
*[`package.xml` line 13 at r4](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6#-Nsd6tZkDJybD-pKXSwc:-Nsd6tZl2hfeu-ah8MMP:b-9q8z18) ([raw file](https://github.com/RobotLocomotion/ros-drake-vendor/blob/e31f5a3fa1077eb16201d9c23b63cbc2ba1f278d/package.xml#L13)):*
> ```XML
>   <maintainer email="drake-users@mit.edu">Drake Users</maintainer>
>   <license>BSD</license>
>

**Review by j-rivero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @jwnimmer-tri)

___
*[`package.xml` line 12 at r4](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6#-Nsd3qxmDyYuctSAT7Jq:-NsyFdws5ZJvHWmStno4:b-8qrphk) ([raw file](https://github.com/RobotLocomotion/ros-drake-vendor/blob/e31f5a3fa1077eb16201d9c23b63cbc2ba1f278d/package.xml#L12)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

What is the expectation for the comprehensiveness of this `<license>` element?  Certainly the majority of Drake's first-party code is `SPDX: BSD-3-Clause`, but Drake vendors a bunch of other code with various open-source licenses.

(If we still need some surgery here then that's fine, but please file a tracking issue to remind us.)
</blockquote></details>

I've created https://github.com/RobotLocomotion/ros-drake-vendor/issues/13 and made a comment on package.xml that refers to the issue. I leave the term "BSD" by now since the field accepts any string and although it may sound vague, it is widely used in the ROS community to refer to BSD-3-Clause.
___
*[`package.xml` line 13 at r4](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6#-Nsd6tZkDJybD-pKXSwc:-NsyG5hv-IhStBAUjjDs:b4pdda4) ([raw file](https://github.com/RobotLocomotion/ros-drake-vendor/blob/e31f5a3fa1077eb16201d9c23b63cbc2ba1f278d/package.xml#L13)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI #12 is related.  For now, we can merge the manually-curated list of dependencies, but eventually we'll need computer assistance with computing this list.
</blockquote></details>

+1 on this. 
___
*[`.github/workflows/ci.yaml` line 22 at r4](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6#-Nsd2HCS1ulFeIBpUd2b:-NsyGim08j2sPIpwG6Uv:b-o2h5gu) ([raw file](https://github.com/RobotLocomotion/ros-drake-vendor/blob/e31f5a3fa1077eb16201d9c23b63cbc2ba1f278d/.github/workflows/ci.yaml#L22)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW These lines seem like they _might_ be a temporary work-around for #10?  If that's so, then we should have a comment nearby explaining, so that we will remember to fix this stanza after its resolved.
</blockquote></details>

Good idea, done in b44b5be
___
*[`.github/workflows/ci.yaml` line 39 at r4](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6#-Nsd35AKBeDQgFHARQXO:-NsyGpo99BdMBBrnyNr8:b-6anrg1) ([raw file](https://github.com/RobotLocomotion/ros-drake-vendor/blob/e31f5a3fa1077eb16201d9c23b63cbc2ba1f278d/.github/workflows/ci.yaml#L39)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It's not clear to me why `drake_cmake_installed_apt` is on this list.  Building that project against the output of `ros-drake-vendor` is not a supported workflow (nor will it ever be).  That project documents that https://drake.mit.edu/apt.html must happen before buliding it, which is not part of this CI job (nor should it be).
</blockquote></details>

Makes sense, removed 94257a9
___
*[`.entrypoint-cmake-make-with-dpkgbuildflags.sh` line 1 at r4](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6#-Nsd1wQh6zceM_fq3i40:-NsyGxJMCUUCkvEWA003:b-erqvbo) ([raw file](https://github.com/RobotLocomotion/ros-drake-vendor/blob/e31f5a3fa1077eb16201d9c23b63cbc2ba1f278d/.entrypoint-cmake-make-with-dpkgbuildflags.sh#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Now that the Dockerfile is gone, is this file dead code that should be removed?

If not, then it probably some comment at the start here to explain the context of how/where it will/should be used.
</blockquote></details>

ouch, removed 607c226

**Review by jwnimmer-tri — APPROVED** [review]
> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @j-rivero)

**Comment by j-rivero** [comment]
@jwnimmer-tri excuse the change after the approval. I wanted to get the green CI before merging and changed the Rolling distro to Humble since Rolling seems to currently have some problems detecting the installation correctly. [6562fe9](https://github.com/RobotLocomotion/ros-drake-vendor/pull/6/commits/6562fe9970cdf39bd04cdf80e75758933a61b110).

**Review by jwnimmer-tri — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/ros-drake-vendor/6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @j-rivero)

**Comment by jwnimmer-tri** [comment]
I'll just merge this now to get something committed onto the main branch.  Future PRs can still improve things.

**Pull request merged**
